# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 987362a9460f5997829051e86bdc94d645108d5903479500292e9cf2d14591f5e95d60b1f9037a782580cd343fda2bcf12f1fc72360d2cabe7aca205470c5a29

test:
  secret_key_base: beea381a9673ccfa902d4b3e9f7e992f2a415d9b992419e43373ad5aaeb1dfd5cb69a54cd2439a52b026dc891fda4c9f3ff7ff89e7d30fc679a5f491a2c3cb92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
